# Generated by Django 5.0.7 on 2024-07-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0003_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='post_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('audio', 'Audio'), ('video', 'Video')], default='text', max_length=20),
        ),
    ]
